mparticle-integrations/mparticle-android-integration-appboy

build.gradle
src/main/java/com/mparticle/kits/AppboyKit.java

- Update to 1.15.3
- Data flush after API calls to Appboy while we're in the background
- Only send email address to Appboy when it changes

Data flush and Email 

---

src/main/java/com/mparticle/kits/AppboyKit.java

Note - I wasn't able to test because I don't have the com.mparticle:android-kit-plugin artifact

Reports SDK Flavor

---

src/main/java/com/mparticle/kits/AppboyKit.java
src/test/java/com/mparticle/kits/AppboyKitTests.java

- Implement IdentityListener callbacks

Make Identity setting logic order-independent

---

src/main/java/com/mparticle/kits/AppboyKit.java

Attempt to parse user attribute value to correct data type.

Implement user attribute value parsing

---

src/main/java/com/mparticle/kits/AppboyKit.java
src/test/java/com/mparticle/kits/AppboyKitTests.java

This will use the "userIdentitificationType" setting to choose the value used for `Appboy#changeUser(String)` call. previously, we were using `customerId` everytime
added unit tests to make sure the setting parsing/application works 
Closes https://go.mparticle.com/work/41098

Honor "userIdentificationType" setting for userId

---

build.gradle
src/main/java/com/mparticle/kits/AppboyKit.java
src/test/java/com/appboy/enums/Month.java
src/test/java/com/mparticle/kits/AppboyKitTests.java

Handle "dob" attribute. Assume it comes in the format "yyyy-MM-dd". If the attribute ("dob") is present, but not formatted correctly, it will be disregarded
Closes https://go.mparticle.com/work/40699

Handle "dob" attribute

---

src/main/java/com/mparticle/kits/AppboyKit.java

See https://github.com/Appboy/appboy-android-sdk/blob/e97b12a2078e8ab614e1bb866c2ab7dac806d41e/CHANGELOG.md#added

Update appboy kit to include SDK Metadata field

---

README.md
example/src/main/AndroidManifest.xml

Fix missing name changes from Appboy -> Braze in README.md
https://github.com/mparticle-integrations/mparticle-android-integration-appboy/issues/56

Update Readme to reflect name change

---

build.gradle
src/main/java/com/mparticle/kits/AppboyKit.java
src/test/java/com/appboy/models/outgoing/AppboyProperties.java
src/test/java/com/braze/models/outgoing/BrazeProperties.java

Update Braze SDK to 18.0.1 - https://github.com/Appboy/appboy-android-sdk/blob/master/CHANGELOG.md#1800

feat: update braze sdk version

---

build.gradle
example/build.gradle
src/main/java/com/mparticle/kits/AppboyKit.java
src/test/java/com/braze/Braze.java
src/test/java/com/braze/BrazeUser.java
src/test/java/com/mparticle/kits/AppboyKitTests.java

Upgrade to Braze SDK v19.0.0
- fix a few breaking naming changes, `Appboy{x}` -> `Braze{x}`

feat: upgrade to Braze 19.0.0

---

gradle.properties
src/main/kotlin/com/mparticle/kits/AppboyKit.kt

- update deprecated function
- remove some unnecessary semi-colons
- fix out of memory error during tests
- kit regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4371

fix: update deprecated function and remove some semi-colons

---

build.gradle

- remove used library causing sonatype fail
- regression tests should pass
- Closes https://go.mparticle.com/work/SQDSDKS-4377

feat: remove used library causing sonatype fail.

---

build.gradle
src/main/kotlin/com/mparticle/kits/AppboyKit.kt
src/test/kotlin/com/braze/Braze.kt
src/test/kotlin/com/braze/BrazeUser.kt

- Updated Braze version and fixed issues with deprecated methods and Braze.kt implementation in tests.
- All test Passed.
- Closes https://go.mparticle.com/work/SQDSDKS-4546

feat: updated Braze version to 23.1.2

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt

- Update the setting key to the new one
- Tested locally and through unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-5493

feat: Update Setting Name to bundleCommerceEventData

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt
src/test/kotlin/com/mparticle/kits/AppboyKitTest.kt

- Manually adding custom attributes for NON PURCHASE EVENTS
- {explain how this has been tested, and what, if any, additional testing should be done}
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5170

fix: Manually adding custom attributes for NON PURCHASE EVENTS

---

src/test/kotlin/com/mparticle/kits/AppboyKitTest.kt

- Changing test for sideloading kits feature
- {explain how this has been tested, and what, if any, additional testing should be done}
- Closes https://mparticle-eng.atlassian.net/browse/SQDSDKS-5551

feat: SQDSDKS-5551 Changing test for sideloading kits feature

---

build.gradle

- Update Braze version to 30.4.0
- Verified through compilation and execution of a local application, as well as running the unit test case to validate the functionality.
- Closes https://go.mparticle.com/work/SQDSDKS-6383

feat: Version update SQDSDKS-6383

---

build.gradle

- Update Braze kit to version 32.1.0 (latest version)
- Ran unit tests and verified functionality with sample application
- Closes https://go.mparticle.com/work/SQDSDKS-6562

feat: Update to Partner latest version 32.1.0

---

build.gradle

- Update Braze kit to version 33.1.0 (latest version)
- Upgrade Kotlin version to work with Braze kit
- Tested these changes with a sample app and ran the unit tests.
- Closes https://go.mparticle.com/work/SQDSDKS-7020

feat: Update to Partner latest version 33.1.0

---

src/test/kotlin/com/mparticle/kits/mocks/MockKitManagerImpl.kt

- cherry-pick commit https://github.com/mparticle-integrations/mparticle-android-integration-appboy/pull/173
- Tested with sample app
- Closes https://go.mparticle.com/work/SQDSDKS-6811

fix:  crossplatform testcase (#173)

---

build.gradle

- This is cherry-pick of this PR https://github.com/mparticle-integrations/mparticle-android-integration-appboy/pull/177
- Tested these changes with a sample app and ran the unit tests.
- Closes https://go.mparticle.com/work/SQDSDKS-7020

feat: Update to Partner latest version 33.1.0 (#177)
