src/main/java/com/mparticle/kits/AppboyKit.java
src/test/java/com/mparticle/kits/AppboyKitTests.java

1) Remove hardcoded cluster mappings
- Previously, we were looking for either a "host" or a "cluster" from the server, the "cluster" would be mapped to a hard-coded "host". This PR alters the behavior in that now, we are only looking for a "host" in the kit settings. We have also removed the hard-code cluster-host mappings
2) Add unit tests
- test that the host is set, when we receive it in the kit settings
- test that we use the default Appboy host (aka do not explicitly set the host), when the "host" is not found in the settings

Remove logic to process Cluster setting

---

src/main/java/com/mparticle/kits/AppboyKit.java
src/test/java/com/appboy/Appboy.java
src/test/java/com/appboy/MockAppboyUser.java
src/test/java/com/appboy/enums/Month.java
src/test/java/com/mparticle/kits/AppboyKitTests.java

h/t @rmi22186, thanks for calling this out!
According to [our docs](https://docs.mparticle.com/integrations/braze/event/#user-attributes), we should be calling `AppboyUser.setDateOfBirth()` with a value derived from the attribute, `UserAttributes.AGE`. We previously were not doing this, so this PR fixes that

Map UserAttributes.AGE to dateOfBirth

---

src/main/java/com/mparticle/kits/AppboyKit.java

We're running into an issue where when using the AppBoy (a.k.a. Braze) kit, we can't set blacklisted views in our implementation.
I don't see why mParticle should bother with setting this for users of the library.
It seems like something not required by the kit, but that should be set by the client.
This is currently preventing us from using the kit, but now of course we're not seeing our data in our Braze console

Remove setting AppBoy blacklisted views

---

src/main/java/com/mparticle/kits/AppboyKit.java
src/test/java/com/appboy/Appboy.java
src/test/java/com/appboy/MockAppboyUser.java
src/test/java/com/appboy/models/outgoing/AppboyProperties.java
src/test/java/com/mparticle/kits/AppboyKitTests.java

Broke out the logic we were using to detect type for UserAttribtues and applied it to custom event Attributes, as well one place we didn't have the logic applied when setting UserAttribtues.
Closes https://go.mparticle.com/work/48843

Enable parsing to implied type for String Attributes

---

README.md
build.gradle
example/build.gradle

Updated `http://` urls to `https://` blocking lint in AGP 7.X upgrade
Check if any other `http://` references exist to upgrade

fix: bugfix https warning

---

src/main/java/com/mparticle/kits/AppboyKit.java

Summary
Food Truck Inc. has reported that when they use our reserved zipcode attribute it gets converted to a number/integer due to enabling the datatype detection in which is needed for other non-reserved attributes. This results in some zipcodes appearing wrong in some cases (for example: inputting "07090" as a zipcode would be forwarded to Braze as 7090).
Testing Plan
Tested the reserved zipcodes both if entered as a string value or a numeric value. Works fine on both whereas in the case of numeric values it would be stringified (in the case for some reason clients were passing reserved zipcode attribute as an integer).

fix: prevent converting stringified zipcode to integer

---

src/main/java/com/mparticle/kits/AppboyKit.java
src/test/java/com/mparticle/kits/TypeDetectionTests.java

Report any type-detected attribute values as part of the `ReportingMessage` generated in `logEvent(MPEvent)`. Previously, we generated a `ReportingMessage` from the original event, even if the `String` values in `customAttributes` were "type-detected" (aka parsed into their non-stringified, primitive type). This change will make it so that the `ReportingMessage` we send to the servers (which ultimately generates a forwarder record in LiveStream) will reflect the "type-detected" attribute values types, rather than them all appearing as Strings

fix: report post-type-detected attribute values

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt

- The logic we have in the Kotlin ports is flawed since willHandlePushMessage will always return false even when push notification is enabled in the UI. Since willHandleMessage always returns false it will never hit the function onPushMessageReceived per our Android SDK code [here](https://github.com/mParticle/mparticle-android-sdk/blob/main/android-kit-base/src/main/java/com/mparticle/kits/KitIntegration.java#L535). I also checked versions before the kotlin port and all of them had the logic in this PR for the fix.
- Was tested locally by setting breakpoints and the value received for willHandlePushMessage was always false and onPushMessageReceived was never hit. After including the not (!) I was able to see onPushMessageReceived being hit.
- Closes …

fix: Push Notification handler fix

---

build.gradle
consumer-proguard.pro
src/main/kotlin/com/mparticle/kits/AppboyKit.kt
src/test/kotlin/com/braze/BrazeUser.kt
src/test/kotlin/com/mparticle/kits/AppboyKitTest.kt

Fixes https://github.com/mparticle-integrations/mparticle-android-integration-appboy/pull/115, https://github.com/mparticle-integrations/mparticle-android-integration-appboy/pull/128 and addresses https://github.com/mparticle-integrations/mparticle-android-integration-appboy/issues/117
The Braze Android SDK v24 replaced the `com.appboy` classpath with `com.braze` as [outlined in the changelog](https://github.com/Appboy/appboy-android-sdk/commit/443b232c545d5127bca0cd36001b5b421385a119).
Currently, this mParticle kit still looks for `com.appboy` which crashes the app. This PR fixes it by replacing all `com.appboy` imports with their `com.braze` equivalents.
|old import|replaced by|
|---|---|
|`com.appboy.enums.Gender`|`com.braze.enums.Gender`| …

chore: bump android-sdk-ui from 23.3.0 to 24.3.0 and replace all com.appboy imports with com.braze

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt
src/test/kotlin/com/mparticle/kits/AppboyKitTest.kt

- All commerce events (both purchase and non-purchase events) forwarded to Braze as a single event with products nested in event properties when bundleProductsWithCommerceEvents set to true.
- All commerce events (both purchase and non-purchase events) forwarded to Braze as expanded individual events for each product when bundleProductsWithCommerceEvents set to false.
- Tested locally and through unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-5428

feat: add order level commerce events

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt
src/test/kotlin/com/mparticle/kits/AppboyKitTest.kt

- An earlier revert undid support for Custom Attributes for purchase events so when it was added for non-purchase events that regression was discovered
- Tested locally and through unit tests
- Closes https://go.mparticle.com/work/SQDSDKS-5170

fix: Forward Custom Attributes for all Commerce Events

---

build.gradle

The recently released [Braze Android SDK v25](https://github.com/braze-inc/braze-android-sdk/blob/master/CHANGELOG.md#2500) is now hosted on Maven Central which means that
```groovy
repositories {
maven { url "https://appboy.github.io/appboy-android-sdk/sdk" }
}
```
can now be removed from `build.gradle`.
Also, the dependency name has been renamed from
```groovy
'com.appboy:android-sdk-ui'
```
to
```groovy
'com.braze:android-sdk-ui'
```
- Ran test suite locally. All tests passed.
- Tested using a locally built artifact `android-appboy-kit-release.aar`. Works OK.

chore: bump android-sdk-ui from 24.3.0 to 25.0.0

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt

- change override function supportsAttributeLists to return true
- No, flag was previously set to true and was changed mistakenly to false
- (https://mparticle-eng.atlassian.net/browse/SQDSDKS-5838)

fix: flip supportsAttributeLists back to true

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt

- To better serve customer data, product requested we update the external id on app launch.
- Verified through compilation of a local application.
- Closes https://go.mparticle.com/work/SQDSDKS-6495

feat: Update External iD on Initialization

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt
src/test/kotlin/com/braze/Braze.kt
src/test/kotlin/com/braze/BrazeUser.kt
src/test/kotlin/com/mparticle/kits/AppboyKitTest.kt

- Added enum values instead of enum for hash event attributes
- Tested with sample application and executed unit test cases
- Closes https://go.mparticle.com/work/SQDSDKS-6544

fix: Add enum value to hash event attributes

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt
src/test/kotlin/com/mparticle/kits/AppboyKitTest.kt

- Added JSON objects to replace BrazeProperties for handling Product Lists, Impression Lists, and Promotion Lists.
- Tested it with a sample application and ran unit tests.
- Closes https://go.mparticle.com/work/SQDSDKS-6543

fix: Convert product list to JSON object when bundling commerce event.

---

src/test/kotlin/com/mparticle/kits/mocks/MockKitManagerImpl.kt

- Migrate internal package’s Migrate CoreCallback class to kotlin (Fix test case related to this changes)
- Executed test case for kits
- Closes https://go.mparticle.com/work/SQDSDKS-6811

fix:  crossplatform testcase

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt
src/test/kotlin/com/mparticle/kits/AppboyKitTest.kt

- Right now, in Android, we send product SKUs to Braze. The product name should also be sent for the native kits, just like we do for the Web kit. If a setting is enabled, the product name should be sent; otherwise, the SKU should be sent to Braze.
- Tested with the sample app and executed unit test cases
- Closes https://go.mparticle.com/work/SQDSDKS-6888

feat: Send ProductName to Braze

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt

- update new server setting 
- Test with sample application
- Closes https://go.mparticle.com/work/SQDSDKS-6888

feat: Add SendProductName Option to Braze

---

build.gradle

- Update Braze kit to version 34.0.0
- Updated the minimum SDK version from 21 (Lollipop) to 25 (Nougat).
- Tested these changes with a sample app and ran the unit tests.
- Closes https://go.mparticle.com/work/SQDSDKS-7028

feat: Update to Partner latest version 34.0.0

---

build.gradle
src/test/kotlin/com/mparticle/kits/mocks/MockUser.kt

- Fix Kit Compatibility Test, added getUserAudiences method
- Verified through compilation of a local application.
- Closes https://go.mparticle.com/work/SQDSDKS-6131

fix: implement new audience api in test mock

---

src/main/kotlin/com/mparticle/kits/AppboyKit.kt
src/test/kotlin/com/braze/BrazeUser.kt
src/test/kotlin/com/mparticle/kits/AppboyKitTest.kt

- We currently support forwarding subscriptionGroupIds mapped via user attributes in our Braze S2S forwarder only, a customer mentioned that Braze support this feature in their Braze and requested this as a feature to our kits, refer to our [docs](https://docs.mparticle.com/integrations/braze/event/#subscription-groups) regarding subscription group ids
- E2E and Unit tested
- Closes https://go.mparticle.com/work/SQDSDKS-7232

feat: Add support to forward SubscriptionGroupIds

---

build.gradle

- update Braze SDK to v35.0.0
- E2E and Unit tested
- Closes https://go.mparticle.com/work/SQDSDKS-7195

feat: Update Braze to v35.0.0
